# Generated by Django 2.2.7 on 2019-11-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userPW',
            new_name='userPw',
        ),
    ]
