# Generated by Django 2.2.7 on 2019-11-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191106_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPw',
            field=models.CharField(max_length=100),
        ),
    ]
